server:
  port: 0

spring:
  application:
    name: userService
  # MongoDB
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/user_db?authSource=admin
#      authentication-database: admin
#      username: rootuser
#      password: rootpass
#      database: user_db
#      port: 27017
#      host: localhost
#      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# JWT
jwt:
  secret:
    key: secret_secret_secret_secret_secret_secret_secret_secret
